#!/bin/bash

xrdb merge ~/.Xresources

killall -q waybar
waybar &

# pgrep -x greenclip >/dev/null || greenclip daemon &
pgrep -x clipman >/dev/null || exec wl-paste -t text --watch clipman store &
pgrep -x dunst >/dev/null || dunst &
pgrep -x auto_backup >/dev/null || ~/scripts/auto_backup &
pgrep -x wpaperd >/dev/null || ~/.local/bin/wpaperd &
pgrep -x gammastep >/dev/null || gammastep -l 38.6914575:-6.4058423 -t 5600:3400 &
